version: "3.7"

services:
  db:
    container_name: segments-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - local
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    container_name: segments-service
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - local
    depends_on:
      db:
        condition: service_healthy

  queue:
    container_name: segments-redis-queue
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - local
    restart: unless-stopped
  
networks:
  local:
    driver: bridge
